rtmp {
    server {
        listen 1935;
        chunk_size 4096;
        ping 30s;
        ping_timeout 10s;

        application live {
            live on;
            record off;
            on_publish http://127.0.0.1:3000/api/admin/events/validate-stream;
            interleave on;
            wait_key on;
            idle_streams off;
            drop_idle_publisher 15s;
            push rtmp://127.0.0.1/hls;
        }

        application hls {
            live on;
            record off;
            hls on;
            hls_nested on;
            hls_cleanup on;
            hls_continuous on;
            hls_fragment 3s;
            hls_playlist_length 18s;
            hls_path /opt/nhanchilltv/nginx/temp/hls_temp;
        }
    }
}
